### PR TITLE
Use cache to test the builded image

### PR DESCRIPTION
**Pull request by yannlugrin**
The test was not testing the published image, so it's better to use cache.

### CODE REVIEW

**Review by WengerK — COMMENTED** [review]
but does it tests the old cached version therefore nop, does it tests the image on docker hub (and then the previous image instead of the new one) ?

**Comment by yannlugrin** [comment]
> but does it tests the old cached version therefore nop, does it tests the image on docker hub (and then the previous image instead of the new one) ?

the `--test-cached` option does not pull the version from the docker registry, so that use the local version if exists. I removed pull-related code as it's not used anymore.

**Comment by yannlugrin** [comment]
And a nice side effect, the action take 2 minutes less as we don't build twice

**Review by WengerK — APPROVED** [review]

**Review by gido — APPROVED** [review]

**Review by WengerK — APPROVED** [review]
🚀

**Review by gido — APPROVED** [review]

**Pull request merged**
