### PR TITLE
PHP 8.0

### PR DESCRIPTION
**Pull request by gido**
### 💬 Describe the pull request
Let's introduce PHP 8.0

### CODE REVIEW

**Comment by gido** [comment]
I'm proposing this now because PHP 8.0 is available on our server:
Screenshot 2020-12-04 at 12 37 46

Let's discuss if we still need a support of Node 12

**Comment by WengerK** [comment]
I think we will need to support node 10 ... 'cause we have many project that need node 10 and we will move them to php 8 :/ - nop ?

- ovv
- ehnv
- resoli

**Comment by gido** [comment]
What is blocking these project to upgrade to nodejs 12 or 14 ?

**Comment by WengerK** [comment]
> What is blocking these project to upgrade to nodejs 12 or 14 ?

My own skills as frontenders. And limitation of th tool we used - not sure how Toolbox is updatable on QS/OVV for example

**Review by WengerK — DISMISSED** [review]

**Review by yannlugrin — DISMISSED** [review]

**Comment by yannlugrin** [comment]
Must be updated with new tests and build structure

**Review by yannlugrin — APPROVED** [review]

**Pull request merged**
